### ISSUE TITLE
[cPP CHANGE] CC Conformance Links

### ISSUE THREAD

**Issue by Kneckter** [appswcpp/repository#1]
**What is the change request for the cPP? Please describe.**
In section 2 of the cPP PDF, the links to the allowed modules/packages only go to the GitHub user page for appswcpp where there isn't a reference to the allowed modules/packages document.

**Describe the solution you'd like**
If the current GitHub repo will be used when this is live, then it would be a good idea to link to the folder that has the PDF (https://github.com/appswcpp/repository/tree/Working/cPP) or to the PDF if the name won't change in the future (https://github.com/appswcpp/repository/blob/Working/cPP/SW%20cPP%20allowed-with%20list.pdf)

**Describe alternatives you've considered**
Letting people find the correct document on their own. 

**Additional context**
This is all you will see with the current link:
![image](https://user-images.githubusercontent.com/16466177/121204719-1543de00-c845-11eb-8fdc-da2a8838bbce.png)

**Comment by bharveyTX** [comment]
Change implemented.
