### ISSUE TITLE
[cPP CHANGE] FMT_SMF.1.1 questions

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#10]
**What is the change request for the cPP? Please describe.**
Two things:

1. "configuration for transmission of sensitive data" should not be in italics since that is not a selection itself
2. should the last two options under sensitive data be separate selections?

While I get that dumpstates and backups contain sensitive data, I don't know that I would think of them as configurations for sensitive data on their own. I'm not sure that needs to be changed, but when I read it, I see these as a little different, even though they are clearly related.

**Describe the solution you'd like**
change from italics on the first bullet

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Fixed italics in adoc / #2 separation not changed.
