### ISSUE TITLE
[cPP CHANGE] dates in related docs for consistency

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#100]
**What is the change request for the cPP? Please describe.**
https://github.com/appswcpp/repository/blame/3a934bf89774ddf71be37e84ea02647fc7fe85c4/cPP/cPP_APP_SW.adoc#L61-L62

These lines only show version numbers but no the dates of publication. For consistency with the other documents listed here dates should probably be added.

**Describe the solution you'd like**
Add the appropriate dates

**Comment by bharveyTX** [comment]
Change Implemented.
