### ISSUE TITLE
[cPP CHANGE] Table 2 filled out

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#104]
**What is the change request for the cPP? Please describe.**
The Security Objectives Rationale table is blank at this point. This should be filled in.

**Comment by bharveyTX** [comment]
As there are no Security Objectives for the TOE, I have removed the table entirely. Will defer to the iTC in next call for inclusion.

**Comment by awnissen** [comment]
Accepting Brandon's resolution.
