### ISSUE TITLE
[cPP CHANGE] FPT_AEX_EXT.1.1 selection instead of assignment?

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#107]
**What is the change request for the cPP? Please describe.**
The SFR is written such that it assumes there will be exceptions and they are assigned. In many cases there will be no exceptions for this, but the way the SFR is written almost points to having to list something. While "no exceptions" would certainly be valid, this could be made more clear if it was changed to a selection.

**Describe the solution you'd like**
Change the assignment to: 

[_selection: no exceptions, [assignment: list of explicit exceptions]_]

It may be useful to slightly modify the SFR text to make the sentence work, but just providing the selection with an explicit "no exceptions" should make it clear to any vendor that this is acceptable.

**Comment by bharveyTX** [comment]
Change implemented.
