### ISSUE TITLE
[cPP CHANGE] assured -> assumed?

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#109]
**What is the change request for the cPP? Please describe.**
https://github.com/appswcpp/repository/blame/3a934bf89774ddf71be37e84ea02647fc7fe85c4/cPP/cPP_APP_SW.adoc#L414

It seems like "assured" here should be "assumed"

I could be missing something, but assured does not seem to make sense.

**Comment by bharveyTX** [comment]
Change implemented.
