### ISSUE TITLE
[cPP CHANGE] FPT_AEX_EXT.1.3 from assignment to selection

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#11]
**What is the change request for the cPP? Please describe.**
Since it is possible that there may be no exceptions for an application, I would think it would be best to make that an explicit choice for the vendor instead of only providing an assignment.

**Describe the solution you'd like**
Change the SFR to the following (bold is the change):

> The application shall be compatible with security features provided by the platform vendor except for _**[selection:** [assignment: list of explicit exceptions]**, no exceptions]**_.

**Describe alternatives you've considered**
N/A

**Additional context**
The ordering of the selection can be either way (i.e. say "no exceptions" first and then the assignment)

**Comment by bharveyTX** [comment]
Change implemented.
