### ISSUE TITLE
[cPP CHANGE] Remove FIA_UAU_EXT.2

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#118]
**What is the change request for the cPP? Please describe.**
While it is clear that FIA_UAU_EXT.2 is expected if the TOE implements its own authentication, it isn't clear what the actual value of this SFR is. The SD EA for it states "it is covered under FIA_UIA_EXT.1", so there isn't a specific test that is independent based on this SFR.

The ECD description of FIA_UAU_EXT.2 states it is only for local password authentication, yet the SFR provides many options for authentication beyond the password, so the SFR seems to be inconsistently described and used.

**Describe the solution you'd like**
Remove the SFR and all references for simplicity. The dependency of FIA_UAU_EXT.5 doesn't make much sense here.

**Comment by bharveyTX** [comment]
Kevin, can you please comment here?

**Comment by miccichek** [comment]
FIA_UAU_EXT.2 and its EA are taken from the NDcPP along with FIA_UIA_EXT.1. This was done for consistency between cPPs.

ECD has been updated to not limit the authentication to local password only.

FIA_UAU_EXT.2 does not have a dependency listed for FIA_UAU_EXT.5.

**Comment by awnissen** [comment]
This issue has been resolved by Kevin's changes.
