### ISSUE TITLE
cPP output generation

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#128]
When generating the output files, especially for the cPP (where the ECD ditaa diagrams are located), the "-r asciidoctor-diagram" parameter should be used.

See https://github.com/itc-wgtools/itc_gentools/blob/master/Direct_Script_Use.adoc for information about how the itc_gentools script works. While most of the information can be used or not, the ditaa translation from text graphics into actual "nice" images requires the diagram component to be installed and explicitly called.

The final output will look better using this on the output (I'm not sure if you are using the Java or another image what the equivalent command line is, though I know there is one).

**Comment by bharveyTX** [comment]
Change implemented!
