### ISSUE TITLE
[cPP CHANGE] T.UNAUTHORIZED_ADMINISTRATOR_ATTACKS MITM

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#13]
**What is the change request for the cPP? Please describe.**
The description here states that an attacker could try to gain access by performing man-in-the-middle attacks, but there is not rationale that would prevent this. FMT_CFG_EXT.1 and FCS_STO_EXT.1 do not deal with network traffic. Either MITM attacks shouldn't be something that are a threat here, or a rationale needs to be added related to a network requirement.

**Describe the solution you'd like**
I would expect there to be a rationale for FTP_DIT_EXT.1 included here. There could also be a rationale for FDP_NET_EXT.1, though I'm less clear on that one since it is just limiting the connections in general.

I would propose this rationale:
> FTP_DIT_EXT.1 specifies the use of secure communication channels to protect data in transit.

This is taken from T.UNTRUSTED_COMMUNICATION_CHANNELS (but limited for the threat).

**Describe alternatives you've considered**
N/A 

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Rationale added to T.UNAUTHORIZED_ADMINISTRATOR_ACCESS
