### ISSUE TITLE
[SD CHANGE] Some tests are bullets, others are not

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#134]
**What is the change request for the SD? Please describe.**
In section 4, a number of the test items are in bullet lists, while in section 2 they are just paragraphs.

**Describe the solution you'd like**
The test presentation should be consistent, regardless of which method is used. Pick one (maybe the bullets since it breaks up the text a little more) and be consistent in all the EA tests.

**Comment by woodbe** [comment]
The Server MOD SD uses both (management uses bullets while AEX uses optional tests).

This change should be reviewed across all SDs

**Comment by bharveyTX** [comment]
In section 4, most of these tests are from FIP 140-2 and the formatting is problematic for bulleted presentation. The ITC does not feel comfortable rephrasing the tests to be bulleted in leau of inducing errors.
