### ISSUE TITLE
[cPP CHANGE] FTP_FIT_EXT.1.1 & Application Note 14

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#14]
**What is the change request for the cPP? Please describe.**
Similar to #6, the selections here for HTTPS, TLS, DTLS and SSH should be listed with the requirement that is currently in the app note.

**Describe the solution you'd like**
The SFR should be written this way (bold for the changes):

>FTP_DIT_EXT.1.1 The application shall [selection:
>- not transmit any data,
>- encrypt all transmitted [selection: sensitive data, data] with [selection: 
>  **- DTLS as specified in the [TLS Package],**
>  **- HTTPS as specified in FCS_HTTPS_EXT.1,**
>  **- SSH as specified in FCS_SSH_EXT.1,**
>  **- TLS as specified in the [TLS Package]**]
>- invoke platform-provided functionality to encrypt all transmitted [selection: sensitive data, data] with [selection: 
>  **- DTLS as specified in the [TLS Package],**
>  **- HTTPS as specified in FCS_HTTPS_EXT.1,**
>  **- SSH as specified in FCS_SSH_EXT.1,**
>  **- TLS as specified in the [TLS Package]**]
>]
>between itself and another trusted IT product.

I'm not sure if the "as specified in" is the right language, but it should be something like this. I re-arranged the selections alphabetically.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Moved selection criteria out of APP note into SFR. Need to discuss with ITC the need to evaluate TLS/DTLS provided by the platform against the TLS package.

**Comment by bharveyTX** [comment]
The iTC determined that TOE or TOE Platform TLS/DTLS must be evaluated according to the TLS package and have implemented this change in the cPP.
