### ISSUE TITLE
[cPP CHANGE] Text conventions in SFRs

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#140]
**What is the change request for the cPP? Please describe.**
Throughout most of the cPP, all assignments and selection text was italicized. For consistency, anything that wasn't had it added. What isn't clear is if this should be the same or not. The conventions listed in the cPP are not exactly clear. I will agree these are taken from the iTC WG-Tools template (which I think were pulled from an example provided by NIAP at some point), but the usage of most of items is not clear within the resulting cPP.

The problem is probably bigger than here, so the short issue is to be consistent in the usage, but there probably should be a discussion as to whether it would be better to make selections and assignments more clearly different.

**Describe the solution you'd like**
Nothing specific at this time, but to provide feedback across the iTCs (through the tools WG or the iTC chairs) to come to some sort of agreed position that could ideally be consistent across all cPPs.

**Describe alternatives you've considered**
Biometrics went with a smaller set, listing all selection and assignment descriptions in italics but making "selection" and "assignment" in bold so they stand out.

**Comment by bharveyTX** [comment]
We will commit these style changes in a later revision of the PP.

**Comment by awnissen** [comment]
Cleaned up style definition during NIAP comment review and addressed issues as identified.

If specific changes are identified, this can be revisited.
