### ISSUE TITLE
[cPP CHANGE] - Iteration Guidance

### ISSUE THREAD

**Issue by bharveyTX** [appswcpp/repository#143]
Add additional language for SFR iteration when an application is claiming multiple TOE Platforms (e.g. Windows & Linux, Platform and Application provided).

**Comment by awnissen** [comment]
Reviewed - Hold off doing until it's a problem.

**Comment by awnissen** [comment]
Closing.  After discussion, this seems pretty self-explanatory.  If it comes up as a TRRT, just tell them "Just iterate it like you would anything else."
