### ISSUE TITLE
[IT REQUEST] Apply RFI 202119?

### ISSUE THREAD

**Issue by KSinitski** [appswcpp/repository#144]
Considering Annex D was reused from NDcPP, should resolution to RFI 202119 also be adopted?

In Annex D.1 the section
*old* The documentation will describe the operation of the entropy source to include how entropy is
produced, and how unprocessed (raw) data can be obtained from within the entropy source for testing
purposes.*/old*

shall be replaced by

*new* The documentation shall describe how unprocessed (raw) data was obtained for the analysis. This
description shall be sufficiently detailed to explain at what point in the entropy source model the data
was collected and what effects, if any, the process of data collection had on the overall entropy
generation rate. */new*.

**Comment by bharveyTX** [comment]
Change implemented.
