### ISSUE TITLE
[cPP CHANGE] Optional Requirements, paragraphs run together

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#15]
**What is the change request for the cPP? Please describe.**
This is just a formatting issue in the output, but the 3 paragraphs of the optional requirements section don't have any spaces between them in the layout. 

**Describe the solution you'd like**
When updating the formatting just make sure there are spaces between the paragraphs so it reads more easily.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented.
