### ISSUE TITLE
[cPP CHANGE] FCS_RBG_EXT.1.2 SFR source(s)

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#16]
**What is the change request for the cPP? Please describe.**
In the SFR selection for the sources, "source" should be changed to "source(s)" to be a little more readable since the vendor may choose multiple source selections but the way the sentence is written it is singular.

**Describe the solution you'd like**
Change these phrases:

>[assignment: number of software-based sources] software-based noise source

to
>[assignment: number of software-based sources] software-based noise source(s)

and change

> assignment: number of hardware-based sources] hardware-based noise source

to
>assignment: number of hardware-based sources] hardware-based noise source(s)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change Implemented.
