### ISSUE TITLE
[cPP CHANGE] FCS_CKM_EXT.1.1 add SFR into selection

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#17]
**What is the change request for the cPP? Please describe.**
The SFR should have the link to FCS_CKM.1 added.

**Describe the solution you'd like**
The SFR should be changed as follows (bolded change):

> The application shall [selection: generate no asymmetric cryptographic keys, invoke platform-provided functionality for asymmetric key generation, implement asymmetric key generation **according to FCS_CKM.1**].

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented, simplified associated app note.
