### ISSUE TITLE
[cPP CHANGE] B.1.4.1 FTP_DIT.1 reference

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#18]
**What is the change request for the cPP? Please describe.**
The SFR reference is incorrect. This is done repeatedly in B.1.4.

**Describe the solution you'd like**
Change FTP_DIT.1 to FTP_DIT_EXT.1

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change Implemented.
