### ISSUE TITLE
[cPP CHANGE] FCS_HTTPS_EXT.1.2 & TLS

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#19]
**What is the change request for the cPP? Please describe.**
Does this requirement mean that if HTTPS is selected that the vendor must also select the TLS requirements since HTTPS must use TLS? This actually makes sense to me, but in that case wouldn't this SFR need to be something like this:

>The TSF shall implement HTTPS using TLS **as defined in the [TLS Package]**.

I'm not sure this is the intent or not, but it would seem to be the outcome.

**Describe the solution you'd like**
Unclear

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Closing without changes per ITC discussion.
