### ISSUE TITLE
[cPP CHANGE] base cPP -> Base-PP

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#2]
**What is the change request for the cPP? Please describe.**
The current "standard" for referring to a base PP is to use "Base-PP", not "base cPP"

**Describe the solution you'd like**
replace all instances of "base cPP" or "base PP" or any similar combination with "Base-PP"

**Describe alternatives you've considered**
N/A

**Additional context**
This was determined while editing the Biometrics PP-Module based on the current CC R5

**Comment by bharveyTX** [comment]
References were changed in the cPP
