### ISSUE TITLE
[cPP CHANGE] FCS_SSH_EXT.1.1 add client/server

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#20]
**What is the change request for the cPP? Please describe.**
The client/server SFRs should be referenced here to make linkage mandatory.

**Describe the solution you'd like**
The SFR should be updated (bold for changes):

>The TSF shall implement SSH acting as [selection: client **according to FCS_SSHC_EXT.1**, server **according to FCS_SSHS_EXT.1**] in accordance with: RFCs 4251, 4252, 4253, 4254, [selection: 4256, 4344, 5647, 5656, 6187, 6668, 8268, 8308, 8332, no other RFCs], and no other standard.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented.
