### ISSUE TITLE
[cPP CHANGE] FIA_X509_EXT.2.1 has "odd" selection list

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#22]
**What is the change request for the cPP? Please describe.**
It appears that this SFR could be added but then "no additional uses" selected, so you would end up with this statement:

> The TSF shall use X.509v3 certificates as defined by RFC 5280 to support authentication for no additional uses.

It isn't clear what this would actually mean since it would seem to say you can use certificates for authentication, but by allowing "no additional uses" it seems to say authentication to nothing.

**Describe the solution you'd like**
I am not sure, since it isn't clear what the intent is the way the SFR reads. I think the simplest answer is to remove that selection choice. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Removed "no additional uses" from the selection.
