### ISSUE TITLE
[SD CHANGE] paragraph spacing

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#23]
**What is the change request for the SD? Please describe.**
In Document Purpose and Overview and the Forward the paragraphs don't have spacing between them so the text is hard to read.

**Describe the solution you'd like**
When updating the docs, check the formatting so extra rows or lines will be added between the paragraphs.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change Implemented
