### ISSUE TITLE
[SD CHANGE] Section numbering is off (and 2 beginning sections)

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#24]
**What is the change request for the SD? Please describe.**
There are 2 section 1s, the Document Purpose and Overview & the Introduction. It seems like the first one should not have been numbered.

Also, the first 2 sections seem to be largely duplicative and that the Overview and Foreword could be combined into a single section.

**Describe the solution you'd like**
Combine the two sections and fix the section numbering.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Resolved with migration to asciidoc.
