### ISSUE TITLE
[SD CHANGE] section 1.2 italics for "and Section 4"

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#25]
**What is the change request for the SD? Please describe.**
In paragraph 6 (in the PDF) the "and Section 4" is in italics but should not be.

**Describe the solution you'd like**
remove italics

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Resolved with migration to asciidoc
