### ISSUE TITLE
[SD CHANGE] 2.1.1.1.3 tests

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#27]
**What is the change request for the SD? Please describe.**
For the invoking platform tests, there is really just one test, but it is listed as 3. On a straight reading, listing Test 1, Test 2 and Test 3 for different platforms implies I need to do all. While it is clear they are conditional, this is all the same test, it is just specified what APIs need to be checked for each platform. 

**Describe the solution you'd like**
The test should be structured like FCS_STO_EXT.1 test which only shows one test and then lists what to do on each separate platform.

**Comment by bharveyTX** [comment]
Change implemented.
