### ISSUE TITLE
[SD CHANGE] FCS_STO_EXT.1 implemented test

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#28]
**What is the change request for the SD? Please describe.**
It seems strange that the only test for this requirement is if the TOE uses platform storage. I would expect there to be something about verifying the location of the credentials (i.e. folder/database, etc) and that the evaluator would at least check that this data isn't in plain text.

**Describe the solution you'd like**
Add a set of test steps to verify the location of the stored credentials and to check they are not stored in plain text (since they are supposed to be stored by some encryption or conditioning).

One of the steps could also be that things like file permissions on the location are proper (i.e. not open to anyone but limited to whatever restricted account or controls are in place). This would seem to be important to check if the TOE is implementing the storage itself.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by bharveyTX** [comment]
There is also no test in the NIAP App Sw PP. While we are not opposed to additional test coverage, we are uncertain of how to author a test case that would provide assurance without mandating source code access or review. 

Also, all files created by the application are subject to the file permissions test in FMT_CFG_EXT.1.2
