### ISSUE TITLE
[cPP CHANGE] PP module -> PP-Module

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#3]
**What is the change request for the cPP? Please describe.**
The current "standard" for a module is to write it as "PP-Module" according to the CC R5

**Describe the solution you'd like**
All instances of "PP module" or similar should be changed to "PP-Module"

**Describe alternatives you've considered**
N/A

**Additional context**
This is how the modules are defines/written in CC R5 CEM

**Comment by bharveyTX** [comment]
Change implemented.
