### ISSUE TITLE
[SD CHANGE] FMT_CFG_EXT.1.2 tests

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#31]
**What is the change request for the SD? Please describe.**
Similar to #27, the tests for each platform are listed as individual test numbers. This should be one test (like FCS_STO_EXT.1) with sections for each platform instead.

**Describe the solution you'd like**
Adjust the test cases to match FCS_STO_EXT.1

**Comment by bharveyTX** [comment]
Change implemented.
