### ISSUE TITLE
[SD CHANGE] 2.4.1.2.3 Windows test

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#34]
**What is the change request for the SD? Please describe.**
The Windows test states:
>The evaluator may also ensure that the /NXCOMPAT flag was used during compilation to verify that DEP protections are enabled for the application.

Is it mandatory to do this check? The way it is written seems like this is optional for the evaluator.

**Describe the solution you'd like**
Unless there is a specific reason for this to be optional (and in that case, this should be described), change "may" to "shall".

**Comment by bharveyTX** [comment]
Replaced may with shall to enforce DEP on Windows platforms.
