### ISSUE TITLE
[SD CHANGE] 2.4.1.5.1 formatting

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#35]
**What is the change request for the SD? Please describe.**
The table in the TSS section has odd fonts compared to the rest of the document, it looks odd to read. Also, the line after the table has a hanging indent at the left page margin instead of the normal indent of all lines.

**Describe the solution you'd like**
correct the formatting, use a consistent table set of fonts.

**Comment by bharveyTX** [comment]
Resolved with asciidoc migration.
