### ISSUE TITLE
[SD CHANGE] 2.5.1.1.2 TSS - no check for no transmission

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#37]
**What is the change request for the SD? Please describe.**
The TSS does not specify explicitly about checking if any data is transmitted. It specifies only that sensitive data should be encrypted. The SFR though states 3 possibilities: no transmission, all data is encrypted, or only sensitive data is encrypted. In the first 2 cases there is no need to know what sensitive data is.

**Describe the solution you'd like**
The TSS section should be rewritten to state that the evaluator shall confirm the use of network transmission first, and then if used, how the traffic is protected. It should also have a note about whether all data is encrypted or just sensitive data, since the documentation should clearly state what is or isn't encrypted.

A suggested text:
> The evaluator shall verify that the TSS describes whether the application transmits any data over a network. If data is transmitted, the TSS shall identify whether all data or only sensitive data is transmitted. It must also identify types of sensitive data transmitted.

**Comment by bharveyTX** [comment]
Change implemented.
