### ISSUE TITLE
[SD CHANGE] 2.5.1.1.4 tests 2 & 3 combined?

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#39]
**What is the change request for the SD? Please describe.**
It isn't clear why there is a test 3. Based on the definition of Sensitive Data in the glossary, credentials are explicitly marked as such, so why there needs to be an explicit test for them is not clear. It should be combined as part of test 2 if credentials are passed. It is likely the easiest way to verify that no sensitive data is transmitted in the clear.

**Describe the solution you'd like**
Add text to the end of Test 2 about checking for credentials being sent by using known values in the testing. This should be done as one part, not as the only check on sensitive data being encrypted, but it doesn't need a separate test.

**Comment by bharveyTX** [comment]
While we agree with this sentiment, we would like to leave test 3 as-is for the additional test coverage and ease of traceability within evaluation test plans.
