### ISSUE TITLE
[cPP CHANGE] Specify iTC interpretation process for adding new platforms

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#4]
**What is the change request for the cPP? Please describe.**
In section 1.3 of the cPP it states that to add a new platform that the vendor should contact the iTC. I would edit this section to point to using the Request for Interpretation process to add new EAs. Further details should not be needed (i.e. that the iTC will decide what to do), as that is part of the process. While this process may not have been fully setup yet, it will need to be by the time the cPP/SD are published.

**Describe the solution you'd like**
Change this:

> To test on a platform for which there are no EAs, a Vendor should contact the iTC with recommended EAs. The iTC will determine if the proposed platform is appropriate for the PP and accept, reject, or develop EAs as necessary in coordination with the technical community.

to this:

> To test on a platform for which there are no EAs, a Vendor will need to initiate a Request for Interpretation with the iTC to add support for the new platform.

**Describe alternatives you've considered**
Remove this entire section instead (this is also perfectly acceptable):

> The only platforms currently recognized by the cPP are those specified in the [SD]. To test on a platform for which there are no EAs, a Vendor should contact the iTC with recommended EAs. The iTC will determine if the proposed platform is appropriate for the PP and accept, reject, or develop EAs as necessary in coordination with the technical community.

**Additional context**
Technically I'm not sure this description even needs to be there at all (since this is the cPP, requesting a change is not necessarily needed to be specified in this document), but if it is going to be, it should point to the iTC processes/methods and not detail them here.

**Comment by bharveyTX** [comment]
A change for platform addition is considerable enough that it would not be a RFI process. The iTC has slightly modified the paragraph for additional clarity.
