### ISSUE TITLE
[SD CHANGE] FIA_X509_EXT.1 "trivially satisfied"

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#40]
**What is the change request for the SD? Please describe.**
I am not certain what the expression "where the ST is therefore claiming that they are trivially satisfied" means. By context it seems this is for when the TOE doesn't support the function, so it doesn't need to do/offer the check. But the particular phrase is not defined that I can see (trivially satisfied), and as such seems to be unclear. The particular phrase seems "odd" when exact conformance is needed, even though it is not in conflict.

**Describe the solution you'd like**
Either the phrase should be defined in the glossary or the text should be changed (the phrase can probably just be removed and be OK).

**Additional context**
This occurs twice and should be edited both times (paragraphs 263 and 277)

**Comment by bharveyTX** [comment]
The ITC feels that the meaning is sufficiently clear and wishes to keep the phrase.
