### ISSUE TITLE
[SD CHANGE] page 75 bullet showing as a "paragraph" but without number

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#42]
**What is the change request for the SD? Please describe.**
This paragraph:
> Since none of these packets will belong to an allowed session, the packets should not be processed by the TOE, and the TOE should not be adversely affected by this traffic. Any results that are unexpected (e.g., core dumps) are candidates for a flaw hypothesis.

shows up with a hanging indent to the left margin. It looks like it should be a bullet that isn't properly formatted, but it could just be a normal paragraph.

**Describe the solution you'd like**
fix the formatting

**Comment by bharveyTX** [comment]
Resolved with asciidoc migration.
