### ISSUE TITLE
[SD CHANGE] Equivalency in both cPP and SD?

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#43]
**What is the change request for the SD? Please describe.**
Is there a reason to have the equivalency appendix in both documents? This seems like a problem since it could lead easily to editor fatigue and different versions accidentally being published in the two documents. As it seems they are the same, it should be picked to be in a single document. I would probably recommend the cPP since the developer will need to look at it specifically to know how to approach the evaluation. It could also be published as a supplement if needed. The SD could point to the cPP (or other supplement) if needed.

**Describe the solution you'd like**
remove one copy of the section and reference that section from all other docs

**Comment by bharveyTX** [comment]
Change implemented, removed appendix from SD.
