### ISSUE TITLE
[MOD CHANGE] SFR categories need "titles"

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#45]
**What is the change request for the Module and which module does this apply? Please describe.**
The SFR categories don't have any titles/descriptions. For example, FMT_SMF.1/Server should list "Specification of Management Functions". This is throughout the docs.

**Describe the solution you'd like**
Add the proper descriptions to the sections.

**Comment by bharveyTX** [comment]
Change implemented with conversion to asciidoc.
