### ISSUE TITLE
[MOD CHANGE] SFR asciidoctor code

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#46]
**What is the change request for the Module and which module does this apply? Please describe.**
The SFRs in the module don't look quite right and need to be reformatted. On my first read I didn't realize that the content under the heading was the actual SFR.

**Describe the solution you'd like**
(None of this will look correct here, it needs to be rendered in asciidoc, this is just the code examples that could be used to achieve the look.)

As an example, FMT_MEC_EXT.1/Server should go from this:

>=== FMT_MEC_EXT.1/Server
>==== FMT_MEC_EXT.1.1/Server
>
>Read and write access to the TOE’s configuration data shall be limited to Administrator, TOE and [assignment: list of authorised entities]

to this:

>=== FMT_MEC_EXT.1/Server
>FMT_MEC_EXT.1.1/Server::
>Read and write access to the TOE’s configuration data shall be limited to Administrator, TOE and [assignment: list of authorised entities]

This will provide something that looks more like what is expected.

An alternative could be this:

>=== FMT_MEC_EXT.1/Server
>\*FMT_MEC_EXT.1.1/Server:\* Read and write access to the TOE’s configuration data shall be limited to Administrator, TOE and [assignment: list of authorised entities]

**Comment by woodbe** [comment]
This also applies to the Agent PP-Module for the SFRs.

**Comment by bharveyTX** [comment]
Change Implemented.
