### ISSUE TITLE
[cPP CHANGE] Consistent convention formatting

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#48]
**What is the change request for the cPP? Please describe.**
The cPP uses one set of set of conventions while the PP-Modules use a different one. Neither seems to be completely followed consistently (especially the PP-Module).

**Describe the solution you'd like**
One standard should be used and pushed consistently across all the documents.

**Comment by bharveyTX** [comment]
Change implemented to use "PP-Module" across all docs.
