### ISSUE TITLE
[cPP CHANGE] Application Note 1 (FCS_RBG_EXT.1 included)

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#5]
**What is the change request for the cPP? Please describe.**
Application Note 1 states 
> If implement DRBG functionality is chosen, then FCS_RBG_EXT.1 shall be included in the ST.

This should be removed and the SFR itself should be edited to this (bold is the change):

> The application shall [selection: use no DRBG functionality, invoke platform-provided DRBG functionality, implement DRBG functionality **according to FCS_RBG_EXT.1**] for its cryptographic operations.

**Describe the solution you'd like**
Remove the noted sentence from Application Note 1 and adjust the SFR to force the link to the other SFR.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented.
