### ISSUE TITLE
[MOD CHANGE] FMT_MEC_EXT.1/Server ECD doesn't match SFR

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#53]
**What is the change request for the Module and which module does this apply? Please describe.**
The ECD for this SFR does not match the text of the requirement in the main body of the document. I think the one on the body is correct, but am not certain (and hence am not providing a pull request).

**Describe the solution you'd like**
correct the mismatch

**Comment by bharveyTX** [comment]
Change implemented.
