### ISSUE TITLE
[MOD CHANGE] General linkage to base-PP

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#54]
**What is the change request for the Module and which module does this apply? Please describe.**
It has been pointed out (see this [reference](https://github.com/biometricITC/cPP-biometrics/issues/300#issue-820082806)) that a PP-Module must refer to all base-PPs that it can be linked with. It isn't clear to me that the current short reference in the PP-Modules is sufficient to meet this requirement.

**Describe the solution you'd like**
Look at NIAP PP-Modules (since those are published at this point) like the VPN Client v2.2 for the types of text that is needed to link the two together.

**Comment by bharveyTX** [comment]
Change Implemented.
