### ISSUE TITLE
[MOD CHANGE] Server MOD FMT_MEC_EXT.1 test tools

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#55]
**What is the change request for the Module and which module does this apply? Please describe.**
In Test 2 there are specific tools listed for Windows and Linux, but there is no tool (or technique) specified for Mac OS. Given that Mac OS is listed as a platform in the cPP SD EAs, there should be some sort of match here. I would expect all the EAs to cover all the platforms that may be considered for testing.

**Describe the solution you'd like**
Add testing for Mac OS.

**Comment by bharveyTX** [comment]
Change implemented.
