### ISSUE TITLE
[cPP CHANGE] FCS_RBG_EXT.1 App Note

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#61]
**What is the change request for the cPP? Please describe.**
Add more detail to the AppNote

**Describe the solution you'd like**
Consider adding:
That AES_CTR must selected in FCS_COP.1/DataEncryption if  CTR_DRBG is selected.
That FCS_COP.1/Hash must be included in the ST if Hash_DBRB is selected
That FCS_COP.1/KeyedHash must be included if HMAC_DRBG is selected.

Assuming, of course, that all that is actually true.

**Describe alternatives you've considered**

**Additional context**
This just makes it more clear for developing validation rules.

**Comment by bharveyTX** [comment]
Change implemented. Added references to FCS_COP iterations in FCS_RBG_EXT.1 selections.
