### ISSUE TITLE
[MOD CHANGE] Document SFR Selection Criteria

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#64]
**What is the change request for the Module and which module does this apply? Please describe.**
Server Module:
Document selection criteria for including these SFRs in the ST: 

FCO_CPC_EXT.1

FIA_X509_EXT.1/ITT/Server (also, I'm pretty sure double iterations are not allowed) - This one says to include it if the "protocols selected utilize X.509 certificates for peer authentication." I don't think there is a selection anywhere for that specific case. (This is a common problem across most PPs. See FTP_ITC_EXT.1 T in Virtualization PP 1.1 for one solution).
https://commoncriteria.github.io/pp/virtualization/virtualization-release.html#FTP_ITC_EXT.1.1

FPT_ITT.1/Server

**Describe the solution you'd like**
If there is a selection for including these selection-based SFRs in the ST, then that should be documented (ideally) both in the App Note of the SFR where the selection is made (if it makes sense) selection and (for sure) in the AppNote for the selection-based SFR. 

If there is no selection for including the selection-based SFR, then it's not a selection-based SFR. 

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered using the existing cPP requirements.

**Additional context**
Add any other context or screenshots about the change request here.

**Comment by bharveyTX** [comment]
We added a clarification to the selection-based SFR appendix as well as additional language to the app note of FPT_ITT.1. We have not found an elegant way to address the double iteration at this time.
