### ISSUE TITLE
[MOD CHANGE] Agent Module: Selection Criteria for X509

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#65]
**What is the change request for the Module and which module does this apply? Please describe.**
This is the same problem as in the Server Module. According to the AppNote the selection criteria for FIA_X509_EXT is whether the protocols selected in FPT_ITT.1/Agent use X509 certificates for peer authentication. The problem is that there is no way from the selections alone to determine whether or not certificates are used or not.

**Describe the solution you'd like**
I would like the selection to make it clear whether or not certificates are used for peer authentication. As an example of how this has been handled elsewhere, see the Virt PP 1.1:
https://commoncriteria.github.io/pp/virtualization/virtualization-release.html#FTP_ITC_EXT.1.1

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered using the existing cPP requirements.

**Additional context**
Add any other context or screenshots about the change request here.

**Comment by bharveyTX** [comment]
We added an app note to FTP_ITT.1 Agent for *FIA_X509_EXT.1.1/ITT/Agent* selection.
