### ISSUE TITLE
[cPP CHANGE] Further clarify for virtualized or containerized applications 

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#67]
**On behalf of CCCS**
cPP Section 1.2 page 9 includes 4 categories of applications, including _"4. Virtualized and Containerized applications (e.g. running in a Docker container)"._ 

cPP Section 1.3 page 10 includes the following description: _"Containerized applications are particularly challenging since their installation packages contain all the support software needed to execute the application. For the purposes of this cPP this support software is considered to be not within the TOE boundary."_ 

This is insufficiently informative explanation of virtualized or containerized applications to inform the reader on how to define the TOE boundary. 

Specifically, cPP v0.58 does not address the question of user space/kernel space (as demonstrated in Figure 1 and Figure 2) for cases of virtualized and containerized applications. This omission results in ambiguity that leaves a number of TOE boundary questions unaddressed. For example, must a virtualized application include (or even specify) Operating System? Another example, could a virtualized application also include an embedded Operating System in the scope? 

To contrast, NDcPP Section 1.2 includes a lengthy explanation of what that cPP considers an acceptable vND, addresses questions of tenancy, and provides specific examples. This allows a greater level of confidence in determining applicability of NDcPP to specific virtualized product types.

**Comment by bharveyTX** [comment]
Addressed with additional language for containers and virtualized applications in section 1. We realize this may not be perfect, but the topic is difficult to address and the ITC is open for further discussion if additional clarification is required.
