### ISSUE TITLE
[cPP CHANGE] Cloud deployments

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#68]
**On behalf of CCCS**
Reading cPP Section 1, it is not clear if cloud deployments are an eligible configuration for certification with this cPP. Cloud environments are explicitly mentioned in Appendix E suggesting they are potentially allowed.

**Comment by bharveyTX** [comment]
Cloud deployments are not explicitly allowed or disallowed. ST authors must specify specific hardware and OS characteristics for the evaluated configuration.
