### ISSUE TITLE
[SD CHANGE] Assurance activities for virtualized or containerized applications

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#69]
**On behalf of CCCS**
In SD v0.39 there does not appear to exist any Assurance Activities (AA) targeted at virtualized or containerized applications. The bare minimum effort is to confirm compatibility with each claimed virtualized or containerized environment.

**Comment by bharveyTX** [comment]
All virtualized applications must perform the same tests depending on the guest OS type. 

We also added language to specify that all Linux OS platform tests are applicable to containers.
