### ISSUE TITLE
[cPP CHANGE] Application Note 3 suggestion

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#7]
**What is the change request for the cPP? Please describe.**
I think the application note could be more concise in its description (or at least a little more clear)

**Describe the solution you'd like**
Suggested text for the application note (bold shows the change):

This requirement is intended to restrict both inbound and outbound network communications to only those required directly by the application. **It does not apply to network communications handled by the platform that may support access to remote filesystems mounted locally by the platform.**

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented.
