### ISSUE TITLE
[cPP CHANGE] Entropy for virtualized/containerized applications

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#70]
**On behalf of CCCS**
It is not clear that entropy generation requirements (as described in the Appendix D. Entropy Documentation and Assessment) include sufficient considerations for virtualized and containerized TOEs.

**Comment by bharveyTX** [comment]
The ITC does not believe that any additional consideration are needed for Appendix D for Entropy Documentation with respect to virtualized or containerized TOEs. The same methodoloy will apply for either the invoke platform or implement functionality selections.
