### ISSUE TITLE
[cPP CHANGE] Services provided by OS v/s TOE

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#71]
**On behalf of CCCS**
The question of services provided by the OS and whether such services are part of the TOE or OE is not fleshed out in this cPP. For example, how to define the TOE boundary for an application that relies on Windows IIS (Internet Information Services) to implement web server? Another example, what is the TOE boundary for an application that integrates with a local database (e.g. SQL Server) that is not exclusive to it?

**Comment by bharveyTX** [comment]
The ITC is still discussing this comment. We believe that all TLS stacks regardless of platform or application provided are sufficiently covered by FDP_DIT_EXT.1 and its associated selections as well as credential storage with FDP_STO_EXT.1. We are also discussing the installation package in TOE boundary discussion.

**Comment by bharveyTX** [comment]
We have updated the TOE boundary definition to include all collateral needed by the application provided as part of its installation packages. In addition, we have added a clarification to the FCS_STO application note for local databases.
