### ISSUE TITLE
[cPP CHANGE] TOE usage

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#73]
**On behalf of CCCS**
cPP Section 1.4 'TOE Usage' fails to provide actual examples of TOE usage or list any specific use cases, instead only offering a reference to cPP Section 1.3.  As applicability of this cPP is likely to become a contentious issue, it is prudent to spend more effort on expanding this section.

**Comment by bharveyTX** [comment]
We included a reference to appropriate examples in the TOE Usage section. Updated section 1.4 to clearly reference section 1.2 with the example provided.
