### ISSUE TITLE
[cPP CHANGE] Conformance to Functional Package for TLS

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#74]
**On behalf of CCCS**
cPP Section 2 'Conformance' includes claims of conformance to Functional Package for TLS. This is a questionable (from the point of view of CC) way to indicate allowed packages as conformance is understood to be to the standard, maybe to the base PP but not to FP. If inclusion of TLS FP is intended to be mandatory for all TOEs, this ought to be indicated in a different way.

**Comment by bharveyTX** [comment]
The TLS Functional Package is only mandatory for TOEs that implement TLS in accordance with FDP_DIT_EXT.1 selections.
