### ISSUE TITLE
[cPP CHANGE] Management functions in FMT_SMF.1

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#75]
**On behalf of CCCS**
cPP Application Note 6 (FMT_SMF.1) needs to categorically explain acceptable ways to implement management functions. Management function could be controlled by policy (set during application installation or via MDM/ESM PM), or via OS permissions, or via direct configuration of the TOE. This is especially relevant, as SPD was rewritten to include assumptions (e.g. A.PROPER_ADMIN) that may be interpreted as the requirement to implement active TOE administration.

**Comment by bharveyTX** [comment]
The ITC does not agree that an assumption facilitates the inclusion of SFRs or SFR operations.

The TOE can be managed by Administrators however the management of roles is not inherently required of the TOE. For instance, the TOE Platform (OS) could perform this functionality. We agree that if the TOE does manage roles then an SFR association is necessary, however, at this time such SFRs are not within scope. This will be considered in a future iteration and linked to issue #72.

**Comment by bharveyTX** [comment]
Enhancement has been implemented see issue #72 for details.
