### ISSUE TITLE
[SD CHANGE] Section 2.3.2.1.3 FMT_SMF.1 Test 1 

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#76]
**On behalf of CCCS**
SD Section 2.3.2.1.3 FMT_SMF.1 Test 1 could be understood as a conditional due to inclusion of "For each option for transmitting sensitive data/PII" verbiage. Arguably, there are some selections in FMT_SMF.1 that may not fall into such a category.  We recommend simplifying, to state "For each selection in FMT_SMF.1" to make Test 1 applicable to all specified management functions.

**Comment by bharveyTX** [comment]
Change implemented.
