### ISSUE TITLE
[cPP CHANGE] FTP_DIT_EXT.1 (Data In Transit)

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#78]
**On behalf of CCCS**
cPP Section 5.6.1.1 FTP_DIT_EXT.1 (Data In Transit). Given the enterprise-focused nature of this cPP, what is the rationale for excluding the IPSEC protocol?

**Comment by bharveyTX** [comment]
This inclusion was discussed during PP development, but there was not enough interest from within the vendor community to leverage this protocol. 

The ITC is open to future requests for inclusion.
