### ISSUE TITLE
[cPP CHANGE] Section 5.4, remove "required"

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#8]
**What is the change request for the cPP? Please describe.**
In the first sentence of the Class section, remove the first "required" from the sentence.

**Describe the solution you'd like**
The sentence should read like this (taking out the first "required")
> Management functions in this section describe required capabilities to support a Security Administrator role and basic set of security management

**Describe alternatives you've considered**
Remove the second "required" instead, but I think it reads better with the first one out.

**Additional context**
Since this is the mandatory SFR section, the functions don't need to be noted as "required", but also having "required" show up twice in 6 words seems like a lot.

**Comment by bharveyTX** [comment]
Change complete.
