### ISSUE TITLE
[cPP CHANGE] SSH Package

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#80]
**On behalf of CCCS**

cPP contains its own version of SSH Protocol SFRs. Why is Functional Package for SSH Version 1.0 not used/included in 'allowed with' list?

**Comment by bharveyTX** [comment]
At the time of this cPP draft release, the SSH Package was not available for incorporation.

The ITC will implement the SSH FP following the conclusion of this comment period.

**Comment by bharveyTX** [comment]
SSH package has been implemented.
