### ISSUE TITLE
[cPP CHANGE] X.509 authentication requirements

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#81]
**On behalf of CCCS**
cPP contains X.509 authentication requirements (FIA_X509_EXT.1&2) but lacks SFR defining certificate  management or CSR generation capability (typically FIA_X509_EXT.3). If certificate-based authentication is in the scope of this cPP, so should be the basic CA and certificate management.

Considering that most modern OS implement trust store (i.e. designated repository for trust anchors) available via standard APIs, it would be prudent to create a requirement to use this platform functionality where it is available. Otherwise we will keep seeing insecure implementations with certificates (e.g. /usr/local/foo/certs/ or "%APPDATA%"\CAs) insecurely stored in various random world-readable locations.

FCS_STO_EXT.1 Application Note 2 mentions " This requirement ensures that persistent credentials (secret keys, PKI private keys, or passwords) are stored securely. If implement functionality to securely store credentials is selected, then the following components must be included in the ST: FCS_COP.1/DataEncryption." . This is insufficient, as it does not cover handling of trusted CA public keys.

**Comment by bharveyTX** [comment]
As the requirement FCS_STO_EXT.1 is currently written, a compliant TOE must either use the platform credential store or implement functionality to securely store secrets via an approved cryptographic operation. 

The storage of secrets in plain text is strictly prohibited by the cPP. 

The ITC does not wish to prohibit a TOE from implementing functionality to store secrets or certificates by mandating the use of the platform certificate store. Should a TOE implement this functionality they are also required to protect these assets using the platform MAC/RBAC capabilities to mitigate risk of tampering.
