### ISSUE TITLE
[cPP CHANGE] Appendix D

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#82]
**On behalf of CCCS**

Appendix D. Entropy Documentation and Assessment fails to explain when producing an EAR is required. Application Note 1 (associated with FCS_RBG_EXT.2.1) fails to tie "use no DRBG functionality" (and perhaps "invoke platform-provided DRBG functionality") to Appendix D or to explicitly state that no EAR is required in such cases.

**Comment by bharveyTX** [comment]
Added application note for explicit inclusion of EAR based on selections in FCS_RBG_EXT.2.1.
