### ISSUE TITLE
[SD CHANGE] FCS_STO_EXT.1 

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#84]
**On behalf of CCCS**
SD v0.39 FCS_STO_EXT.1 does not provide 'for java:' case in Test 1 to allow use of Java KeyStore API that is functionally equivalent to the other provided choices. This creates artificial and unnecessary difficulties for certifying applications written in Java.

**Comment by bharveyTX** [comment]
This issue has some history and for this release of the Protection Profile, the use of Java in this context shall select "implement functionality" in FCS_STO_EXT.1. 

The addition of Java or the JVM as a TOE Platform may be requested in future versions following the procedures detailed in the TOE Boundary section of the cPP.
