### ISSUE TITLE
[SD CHANGE] Hardware components listing

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#86]
**On behalf of the CCCS**
SD page 69 para 319 mentions "The developer shall provide documentation identifying the list of software and **hardware components** that compose the TOE. Hardware components should identify at a minimum the processors used by the TOE. "

- Should hardware components be in the scope of AVA activities in the Application Software cPP?
- The scope of developer disclosure in context of AVA is especially important since FPT_LIB_EXT.1 Use of Third Party Libraries have been removed, leaving AVA_VAN as the only requirement mandating disclosing third-party libraries. Please further clarify what is considered “software … components that compose the TOE” and how to identify them.

**Comment by bharveyTX** [comment]
We have removed hardware documentation requirements from the SD.

The ITC believes that this cPP targets applications that are capable of executing on general purpose compute hardware with general purpose operating systems and therefore such detail is unnecessary at the hardware level.
