### ISSUE TITLE
[SD CHANGE] Software components wrt AVA activities

### ISSUE THREAD

**Issue by avcode79** [appswcpp/repository#87]
**On behalf of the CCCS**
SD page 69 para 319 mentions " Software components include applications, the **operating system** and other major components that are independently identifiable and reusable. "

1. Should operating system be in the scope of AVA activities in the Application Software cPP?
2. The scope of developer disclosure in context of AVA is especially important since FPT_LIB_EXT.1 Use of Third Party Libraries have been removed, leaving AVA_VAN as the only requirement mandating disclosing third-party libraries. Please further clarify what types of software components must be disclosed and how to identify them.

**Comment by bharveyTX** [comment]
The OS must be identified for testing and equivalency purposes but is out of scope for AVA activities.
