### ISSUE TITLE
[cPP CHANGE] FMT_CFG_EXT.1.1 and generated credentials (Application Note 4)

### ISSUE THREAD

**Issue by woodbe** [appswcpp/repository#9]
**What is the change request for the cPP? Please describe.**
This sentence is confusing (only after re-reading it several times and trying to write this issue did I think I finally understand it):
> Credentials that are generated during installation using requirements laid out in FCS_RBG_EXT.1 are not by definition default credentials.

I think this sentence should be changed to:
> Credentials generated during or after the installation using requirements laid out in FCS_RBG_EXT.1 are not by definition default credentials.

Since different configurations could have these generated during the install or others on first use, specifying the "installation" I think is what confused me.

**Describe the solution you'd like**
Not sure, I'm confused by the description

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bharveyTX** [comment]
Change implemented.
