### ISSUE TITLE
[cPP CHANGE] FCS_CKM.1/Asymmetric mal-formatted

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#96]
**What is the change request for the cPP? Please describe.**
The "and specified key sizes..." language at the end of the requirement are presented as part of the last selection. That should be pulled out.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
You might want to rename this as FCS_CKM.1/AK or /AKG. It's not important, but that seems to be the direction this requirement is heading.

**Comment by bharveyTX** [comment]
Change implemented. Added new line to asciidoc to render closing selection bracket more clearly.
