### ISSUE TITLE
[cPP CHANGE] FCS_CKM.2 Selection criteria? 

### ISSUE THREAD

**Issue by robertmclemons** [appswcpp/repository#97]
**What is the change request for the cPP? Please describe.**
Where is the selection to bring FCS_CKM.2 in to the ST? This should be documented in the App Note.

**Describe the solution you'd like**
According to the TLS and SSH Packages, they both require CKM.2, so this SFR should be included at least when TLS, DTLS, or SSH is selected in DIT.

**Describe alternatives you've considered**
Maybe somewhere else, I don't know.

**Additional context**
All selection-based requirements should depend on one or more specific selections.

**Comment by bharveyTX** [comment]
Change implemented, additional language added to FTP_DIT for FCS_CKM.2 inclusion.
